@startuml Bungalow Booking Class Diagram
class User{
    firstName: string
    lastName: string
    email: string
    age: number
    bookings: [Booking]
    reviews: [Review]
    ownedBungalows: [Bungalow]

    constructor(firstName: string, lastName: string, email: string, age: number)
    book(bungalow: Bungalow, checkInDate: Date, checkOutDate: Date)
    review(bungalow: Bungalow, text: string, rate: number)
    pay()
    cancelBooking(booking: Booking)
    signUp(firstName: string, lastName: string, email: string, password: string)

    setPrice(bungalow: Bungalow, price: number)
    disableDates(bungalow: Bungalow, startDate: Date, endDate: Date)
    deleteBungalow(bungalow: Bungalow)
    createBungalow(location: string, name: string, price: number, capacity: number)
}

class Bungalow{
    id: number
    name: string
    location: string
    capacity: number
    price: number
    owner: User
    bookings: [Booking]
    bookedDates: [Date]
    reviews: [Review]
    images: [string]
    services: [string]
    get rating(): number

    checkAvailability(checkInDate: Date, checkOutDate: Date,)

}

class Booking{
    id: number
    guest: User
    bungalow: Bungalow
    checkInDate: Date
    checkOutDate: Date
    review: Review
    cancelled: boolean
    get status(): string
    get bookingDates() : [string]
    get totalPrice(): number

    constructor(guest: User, bungalow: Bungalow, checkInDate: Date, checkOutDate: Date)
    cancel()
}

class Review {
    message: string
    rate: number
    author: User
}

class Payment{
    amount: number
}

Bungalow *- Review
User --> Review
User "1" o-->"0..*" Booking
Booking "1" o-->"1" User
Booking "1" <--o "1" Bungalow
Booking o--> Bungalow
Booking o-> Payment

@enduml